---
title: "Innkalling, første møte i styringsgruppen for prosjektet *Modernisering av Rapporteket* (MAR)"
author: "Are Edvardsen, SKDE; Saana Heinänen, HN-IKT"
date: "Mandag 12\\. november 2018"
params:
  tableFormat: "html"
header-includes:
  - \usepackage[english, norsk]{babel}
  - \usepackage{booktabs}
  - \usepackage{rotating}
# output:
#   #beamer_presentation: default
#   #word_document: default
#   pdf_document: default
  #html_document: default
---

```{r settings, echo=FALSE, include=FALSE}
library(magrittr)
library(knitr)
library(kableExtra)
options(knitr.table.format = params$tableFormat)
knitr::opts_chunk$set(warnings=FALSE,echo=FALSE)
options(stringsAsFactors=FALSE)
Sys.setlocale("LC_TIME", "nb_NO.UTF-8")
```

```{r makeStandardTableFunction, eval=TRUE}
mst <- function(tab, type = params$tableFormat, cap = NULL, digs = 0, align = NULL, fs = 8, lsd = FALSE) {
  if (type == "latex") {
    if (lsd) {
      lo <- c("hold_position", "scale_down")
    } else {
      lo <- c("hold_position")
    }
    k <- kable(tab, caption = cap, digits = digs, align = align,
               booktabs = TRUE) %>% 
      kable_styling(latex_options = lo, font_size = fs)
  }
  
  if (type == "html") {
    k <- kable(tab, caption = cap, digits = digs, align = align) %>% 
      kable_styling(bootstrap_options = c("striped", "hover", "condensed"),
                    full_width = F)
  }
  print(k)
}
```

## Møtet
```{r motet, echo=FALSE, results='asis'}
Egenskap <- c("Tid", "Sted", "Telefon", "Videokonferanse over helsenettet",
              "Skype", "Video utenfor helsenettet")
Verdi <- c("Mandag 12. november 2018 kl 1200 -- 14:00",
           "UNN Breivika Tromsø, C0.513 (møterom SKDE)",
           "77 60 21 00, konferanse ID 997515",
           "997515",
           "997515@uc.nhn.no eller tos.felles.c0-513@uc.nhn.no",
           "Gå til siden https://join.nhn.no/ (installere klient), velg Delta i samtale (Join call), tast inn Samtale ID (Call ID) 997515 (Kode ikke nødvendig) og tast inn navnet ditt. Krever Chrome")
tab <- data.frame(Egenskap, Verdi)
if (params$tableFormat == "latex") {
  align <- c("l", "p{6cm}")
} else {
  align <- c("l", "l")
}
mst(tab, align = align)
```

# Deltagere

## Styringsgruppen
```{r styringsgruppen, echo=FALSE, results='asis'}
Navn <- c("Eva Stensland", "Trym Mathisen", "Rune Grimstad",
          "Bernt Olav Økland", "Sissel Jor", "Ågot Ligaarden", "Jørn Hansen")
Rolle <- c("Helse Nord/prosjekteier", "Helse Nord/prosjekteier", "Helse Midt",
           "Helse Vest", "Helse Sør-Øst", "Norsk Helsenett", "FMK, NIKT HF")
tab <- data.frame(Navn, Rolle)
mst(tab)
```


## Øvrige
```{r ovrige, echo=FALSE, results='asis'}
Navn <- c("Saana Heinänen", "Are Edvardsen", "Øvrige")
Rolle <- c("Prosjektleder HN-IKT", "Prosjektleder SKDE", "Prosjektgruppen")
tab <- data.frame(Navn, Rolle)
mst(tab)
```


# Program

## Tidsskjema
```{r program, echo=FALSE, results='asis'}
Sak <- as.character(seq(1,6))
Tid <- c("12:00", "12:05", "12:15", "12:45", "13:15", "13:45")
Tema <- c("Godkjenning av innkalling og saksliste",
          "Orientering om bakgrunn og innretning til prosjektet",
          "Orientering om status for prosjektet",
          "Spørsmål og innspill",
          "Styrets arbeidsform, informasjonsflyt og møteplan",
          "Eventuelt")
Ansvarlig <- c("Styringsgruppens leder", "PL", "PL", "Styringsgruppen", "Styringsgruppen",
               "Styringsgruppen/PL")

tab <- data.frame(Sak, Tid, Tema, Ansvarlig)
mst(tab, lsd = TRUE)
```
